apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule : "*/1 * * * *"  # Schedule is a cron expression, just like a linux cron expresssion
  jobTemplate: 
    spec: # this is a job specification
      template: 
        spec: # This is the pod specification
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernestes cluster
          restartPolicy: OnFailure