apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  template: # Similar to deployment; the template is a pod specification
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4 # How many times to try in the case of failure.