apiVersion: apps/v1
kind: Deployment # a deployment will be managing a set of pods.
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    # The selector let the deployment object to identify which groups of pod should manage.
    matchLabels:
      app: nginx
  template: # the template is very similar to the declaration of a Pod object
    metadata:
      # It is important that this label match with the selector labels otherwise deployment 
      # will create unmanaged pods by the declared deployment.
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
