apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-deployment
  namespace: pizza
spec:
  replicas : 3
  selector:
    matchLabels:
      app: toppings-svc
  template:
    metadata:
      labels:
        app: toppings-svc
    spec:
      containers:
      - name: pizza-service
        image: linuxacademycontent/pizza-service:1.14.6
        command: ['nginx']
        args: ["-g", "daemon off;"]
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 80
      